<!-- 
    will contain PostgreSQL, EF Core, file storage, external APIs, notifications, 
    and other technical implementations.
 -->

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GymPi.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymPi.Application\GymPi.Application.csproj" />
    <ProjectReference Include="..\GymPi.Domain\GymPi.Domain.csproj" />
  </ItemGroup>
</Project>
