// <auto-generated />
using System;

using GymPi.Infrastructure.Persistence;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GymPi.Infrastructure.Persistence.Migrations;

[DbContext(typeof(GymPiDbContext))]
[Migration("20260915121500_CreateHouseholdProfiles")]
partial class CreateHouseholdProfiles
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("GymPi.Domain.Profiles.HouseholdProfile", profile =>
        {
            profile.Property<Guid>("Id")
                .ValueGeneratedNever()
                .HasColumnType("uuid")
                .HasColumnName("id");

            profile.Property<DateTimeOffset>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            profile.Property<int>("DailyHydrationGoalMl")
                .HasColumnType("integer")
                .HasColumnName("daily_hydration_goal_ml");

            profile.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnType("character varying(80)")
                .HasColumnName("display_name");

            profile.Property<string>("TimeZoneId")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("time_zone_id");

            profile.HasKey("Id")
                .HasName("pk_household_profiles");

            profile.ToTable(
                "household_profiles",
                table => table.HasCheckConstraint(
                    "ck_household_profiles_hydration_goal",
                    "daily_hydration_goal_ml BETWEEN 250 AND 10000"));
        });
#pragma warning restore 612, 618
    }
}
