// <auto-generated />
using System;

using GymPi.Infrastructure.Persistence;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace GymPi.Infrastructure.Persistence.Migrations;

[DbContext(typeof(GymPiDbContext))]
partial class GymPiDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("GymPi.Domain.Hydration.HydrationEntry", entry =>
        {
            entry.Property<Guid>("Id")
                .ValueGeneratedNever()
                .HasColumnType("uuid")
                .HasColumnName("id");

            entry.Property<int>("AmountMl")
                .HasColumnType("integer")
                .HasColumnName("amount_ml");

            entry.Property<DateTimeOffset>("ConsumedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("consumed_at_utc");

            entry.Property<Guid>("ProfileId")
                .HasColumnType("uuid")
                .HasColumnName("profile_id");

            entry.HasKey("Id")
                .HasName("pk_hydration_entries");

            entry.HasIndex("ProfileId", "ConsumedAtUtc")
                .HasDatabaseName("ix_hydration_entries_profile_consumed_at");

            entry.ToTable(
                "hydration_entries",
                table => table.HasCheckConstraint(
                    "ck_hydration_entries_amount",
                    "amount_ml BETWEEN 1 AND 5000"));
        });

        modelBuilder.Entity("GymPi.Domain.Profiles.HouseholdProfile", profile =>
        {
            profile.Property<Guid>("Id")
                .ValueGeneratedNever()
                .HasColumnType("uuid")
                .HasColumnName("id");

            profile.Property<DateTimeOffset>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at_utc");

            profile.Property<int>("DailyHydrationGoalMl")
                .HasColumnType("integer")
                .HasColumnName("daily_hydration_goal_ml");

            profile.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnType("character varying(80)")
                .HasColumnName("display_name");

            profile.Property<string>("TimeZoneId")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("time_zone_id");

            profile.HasKey("Id")
                .HasName("pk_household_profiles");

            profile.ToTable(
                "household_profiles",
                table => table.HasCheckConstraint(
                    "ck_household_profiles_hydration_goal",
                    "daily_hydration_goal_ml BETWEEN 250 AND 10000"));
        });

        modelBuilder.Entity("GymPi.Domain.Hydration.HydrationEntry", entry =>
        {
            entry.HasOne("GymPi.Domain.Profiles.HouseholdProfile", null)
                .WithMany()
                .HasForeignKey("ProfileId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired()
                .HasConstraintName(
                    "fk_hydration_entries_household_profiles_profile_id");
        });
#pragma warning restore 612, 618
    }
}
